services:
  redis:
    image: redis/redis-stack:latest
    ports:
      - 6379:6379
      - 8001:8001
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]

  graphql:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    ports:
      - 8080:8080